volumes:
  threat_vol:

services:
  api:
    container_name: threatapi
    build:
      context: ../app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../app:/app
      - ../data:/data
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - LLM_GEMINI_KEY=${GEMINI_API_KEY}
      - LLM_MODEL=${LLM_MODEL:-gemini-2.0-flash-exp}
      - NUM_RESULTS=${NUM_RESULTS:-10}
      - DATABASES=${DATABASES:-db/cve.db:containers,db/cve.db:windows,db/mitre.db:containers,db/mitre.db:windows}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-jina-embeddings-v2-small-en}
